### ISSUE TITLE
Come up with a project name

### ISSUE THREAD

**Issue by amirmc** [ocamllabs/cosmetrics#1]
List thoughts here for possible names for this project/tool.  It's initially being developed using the MirageOS libs as a a test case but should be useable by anyone who wishes to track progress on open source projects.

**Comment by amirmc** [comment]
ossmetry? ossmetrics? somewhat descriptive and also pronounceable.  could just drop an 's' (osmetry).

**Comment by samoht** [comment]
cosmetrics (code-source metrics) :p

**Comment by Drup** [comment]
My vote goes for cosmetrics. :D
